# Generated by Django 5.1.3 on 2024-12-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
