# Generated by Django 5.1.3 on 2024-12-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
